dist: trusty
sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - export DEBIAN_FRONTEND=noninteractive;
  - sudo apt-get -qq --yes update
  - npm install

test:
  - echo "no tests"

script:
  - npm run build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t gaspt .;
      docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
      docker tag gaspt gerardabello/gaspt;
      docker push gerardabello/gaspt;
    fi
